[package]
name = "ferric_macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macros for the Ferric framework"
keywords = ["wasm", "webassembly", "frontend", "framework", "macros"]
categories = ["wasm", "web-programming", "development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
darling.workspace = true

